### PR TITLE
feat: improve API by returning a Zeno object from auth to issue uploads

### PR DESCRIPTION
**Pull request by Sparkier**
The API has been changed so that after authentication, the user gets a Zeno object to issue API commands on. This object automatically manages user handling and token refresh.

### CODE REVIEW

**Comment by Sparkier** [comment]
This goes in the direction of what @cabreraalex suggested [here](https://github.com/Sparkier/zeno_hub/pull/54#issuecomment-1682470169).

**Comment by Sparkier** [comment]
To test, one can use this script:

```
"""Uploading existing zeno chatbot project to a zeno backend using the Zeno API."""
import argparse
import ast
import json
from pathlib import Path

import pandas as pd
from pandas.api.types import (
    is_bool_dtype,
    is_datetime64_any_dtype,
    is_numeric_dtype,
    is_string_dtype,
)

import zeno_api
from zeno_api import MetadataType

parser = argparse.ArgumentParser(
    prog="Upload OpenAI Chat data.",
    description="Uploads data for an OpenAI Chat report that has been saved as a csv "
    "to a new Zeno project.",
)
parser.add_argument("--csv_path")
parser.add_argument("--connex_username")
parser.add_argument("--connex_password")
args = parser.parse_args()


def resolve_column_type(df: pd.DataFrame, col: str) -> MetadataType:
    """Get the Zeno MetadataType of a pandas dataframe column.

    Args:
        df (pd.DataFrame): dataframe for which to get the column type.
        col (str): name of the column for which to get the type.

    Returns:
        MetadataType: the metadata type of the column.
    """
    if is_bool_dtype(df[col]):
        return MetadataType.BOOLEAN
    if is_datetime64_any_dtype(df[col]):
        return MetadataType.DATETIME
    if is_string_dtype(df[col]):
        return MetadataType.NOMINAL
    if is_numeric_dtype(df[col]):
        return MetadataType.CONTINUOUS
    return MetadataType.OTHER


zeno = zeno_api.authenticate(args.connex_username, args.connex_password)
uuid = zeno.create_project("chatbot test", view="openai-chat")

data_frame = pd.read_csv(args.csv_path)
data_frame = data_frame.fillna("")
output_cols = list(
    filter(lambda col: str(col).startswith("OUTPUToutput"), data_frame.columns)
)
models = list(
    set(list(map(lambda col: str(col).replace("OUTPUToutput", ""), output_cols)))
)
predistill_cols = list(
    filter(lambda col: str(col).startswith("PREDISTILL"), data_frame.columns)
)
postdistill_cols = list(
    filter(lambda col: str(col).startswith("POSTDISTILL"), data_frame.columns)
)

file_path = Path("data.json")
for index, row in data_frame.iloc[:20].iterrows():
    with open(file_path, "w") as f:
        messages_obj = ast.literal_eval(row["messages"])
        json.dump(messages_obj, f)
    datapoint_name = f"{index}.json"
    zeno.upload_datapoint(file_path, datapoint_name)
    zeno.add_label(datapoint_name, row["label"])
    for col in output_cols:
        model_name = str(col).replace("OUTPUToutput", "")
        zeno.add_output(datapoint_name, model_name, row[str(col)])
    for col in predistill_cols:
        col_name = str(col).replace("PREDISTILL", "")
        type = resolve_column_type(data_frame, str(col))
        zeno.add_predistill(datapoint_name, col_name, row[str(col)], type)
    for col in postdistill_cols:
        col_name = str(col).replace("POSTDISTILL", "")
        type = resolve_column_type(data_frame, str(col))
        model = ""
        for m in models:
            if col_name.endswith(m):
                model = m
                col_name = col_name.replace(m, "", 1)
        zeno.add_postdistill(datapoint_name, col_name, model, row[str(col)], type)

file_path.unlink()
```

**Comment by cabreraalex** [comment]
Epicccc. Do you think it would make sense to make it slightly modified like this:

```
import zeno_api

zeno = zeno_api.authenticate(<username>, <password>)
project = zeno.create_project(<project_name>)
project.upload_datapoint(...)
project.upload_label(...)
...

**Comment by Sparkier** [comment]
> Epicccc. Do you think it would make sense to make it slightly modified like this:
> 
> ```
> import zeno_api
> 
> zeno = zeno_api.authenticate(<username>, <password>)
> project = zeno.create_project(<project_name>)
> project.upload_datapoint(...)
> project.upload_label(...)
> ...
> ```
> 
> Or maybe we just call it `get_project` and it makes the project if it doesn't exist, or updates it with new settings.

Had this at first but decided against it, now agree that this is better than the somewhat clunky uuid handling.

We can't really to the `get_project` I think because except for UUID there is no attribute that directly identifies a project.

**Review by cabreraalex — APPROVED** [review]

**Pull request merged**
